## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Mataura,NZ,-46.1927,168.8643,66.61,60,100,2.75,light rain
1,1,Pombas,CV,17.1503,-25.0201,69.58,69,11,10.31,few clouds
2,2,Bluff,NZ,-46.6000,168.3333,62.94,76,100,8.08,overcast clouds
3,3,Sur,OM,22.5667,59.5289,79.57,51,0,12.62,clear sky
4,4,Jamestown,US,42.0970,-79.2353,42.44,50,100,5.75,overcast clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 50
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Mataura,NZ,-46.1927,168.8643,66.61,60,100,2.75,light rain
1,1,Pombas,CV,17.1503,-25.0201,69.58,69,11,10.31,few clouds
2,2,Bluff,NZ,-46.6000,168.3333,62.94,76,100,8.08,overcast clouds
3,3,Sur,OM,22.5667,59.5289,79.57,51,0,12.62,clear sky
5,5,Busselton,AU,-33.6500,115.3333,61.12,60,0,9.82,clear sky
6,6,Tuatapere,NZ,-46.1333,167.6833,66.69,69,100,5.77,light rain
7,7,Rikitea,PF,-23.1203,-134.9692,78.24,64,69,11.56,broken clouds
9,9,Maceio,BR,-9.6658,-35.7353,76.44,88,20,2.30,few clouds
11,11,Kushima,JP,31.4583,131.2333,64.51,48,1,1.72,clear sky
12,12,San Policarpo,PH,12.1791,125.5072,81.93,86,86,15.57,light rain

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                427
City                   427
Country                421
Lat                    427
Lng                    427
Max Temp               427
Humidity               427
Cloudiness             427
Wind Speed             427
Current Description    427
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Mataura,NZ,-46.1927,168.8643,66.61,60,100,2.75,light rain
1,1,Pombas,CV,17.1503,-25.0201,69.58,69,11,10.31,few clouds
2,2,Bluff,NZ,-46.6000,168.3333,62.94,76,100,8.08,overcast clouds
3,3,Sur,OM,22.5667,59.5289,79.57,51,0,12.62,clear sky
5,5,Busselton,AU,-33.6500,115.3333,61.12,60,0,9.82,clear sky
...,...,...,...,...,...,...,...,...,...,...
658,658,Nargana,PA,9.4428,-78.5906,79.52,86,100,1.97,overcast clouds
660,660,Porto Novo,BJ,6.4965,2.6036,84.02,79,99,7.20,overcast clouds
661,661,Preston,GB,53.7667,-2.7167,51.33,92,100,5.01,overcast clouds
662,662,Arenapolis,BR,-14.4503,-56.8461,73.35,79,2,1.01,clear sky
664,664,Ratnagiri,IN,16.9833,73.3000,79.63,82,100,2.24,overcast clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Mataura,NZ,66.61,light rain,-46.1927,168.8643,
1,Pombas,CV,69.58,few clouds,17.1503,-25.0201,
2,Bluff,NZ,62.94,overcast clouds,-46.6000,168.3333,
3,Sur,OM,79.57,clear sky,22.5667,59.5289,
5,Busselton,AU,61.12,clear sky,-33.6500,115.3333,
6,Tuatapere,NZ,66.69,light rain,-46.1333,167.6833,
7,Rikitea,PF,78.24,broken clouds,-23.1203,-134.9692,
9,Maceio,BR,76.44,few clouds,-9.6658,-35.7353,
11,Kushima,JP,64.51,clear sky,31.4583,131.2333,
12,San Policarpo,PH,81.93,light rain,12.1791,125.5072,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"    

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Hotel not found...Skipping.")

Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df=hotel_df.loc[(hotel_df["Hotel Name"]!='')]
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Mataura,NZ,66.61,light rain,-46.1927,168.8643,Ellie's Villa
1,Pombas,CV,69.58,few clouds,17.1503,-25.0201,Paul Paradis
2,Bluff,NZ,62.94,overcast clouds,-46.6000,168.3333,Bluff Homestead - Guesthouse & Campervan Park
3,Sur,OM,79.57,clear sky,22.5667,59.5289,Sur Plaza Hotel
5,Busselton,AU,61.12,clear sky,-33.6500,115.3333,Observatory Guest House
...,...,...,...,...,...,...,...
658,Nargana,PA,79.52,overcast clouds,9.4428,-78.5906,Dubbir
660,Porto Novo,BJ,84.02,overcast clouds,6.4965,2.6036,Tour Eiffel Hotel Benin
661,Preston,GB,51.33,overcast clouds,53.7667,-2.7167,Legacy Preston International Hotel - managed b...
662,Arenapolis,BR,73.35,clear sky,-14.4503,-56.8461,Mato Grosso Hotel
664,Ratnagiri,IN,79.63,overcast clouds,16.9833,73.3000,Hotel Landmark

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))